In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F



In [2]:
with open('data/anna.txt', 'r') as f:
    text = f.read()

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [4]:
#분리하기 set으로 중복제거하고
chars = tuple(set(text))

In [5]:
chars

('4',
 '%',
 '-',
 '*',
 'k',
 'f',
 '&',
 'A',
 '/',
 'P',
 'q',
 '0',
 '3',
 'F',
 'L',
 ';',
 'D',
 ' ',
 'y',
 'Z',
 'j',
 ',',
 'V',
 's',
 'E',
 '?',
 'X',
 'C',
 'J',
 'O',
 'R',
 '6',
 '$',
 'n',
 'h',
 'm',
 't',
 '(',
 'w',
 '.',
 'H',
 'i',
 '"',
 'z',
 'Y',
 '8',
 '\n',
 'I',
 '2',
 '7',
 'r',
 'Q',
 'd',
 '_',
 'g',
 '!',
 '9',
 'l',
 'e',
 'o',
 'T',
 ')',
 'S',
 ':',
 'U',
 'G',
 'W',
 "'",
 '`',
 'v',
 'N',
 '1',
 'a',
 'M',
 '5',
 'p',
 'c',
 '@',
 'K',
 'b',
 'B',
 'x',
 'u')

In [6]:
#번호 붙이기
#key 가 숫자 value 가 글자
int2char = dict(enumerate(chars))

In [7]:
int2char

{0: '4',
 1: '%',
 2: '-',
 3: '*',
 4: 'k',
 5: 'f',
 6: '&',
 7: 'A',
 8: '/',
 9: 'P',
 10: 'q',
 11: '0',
 12: '3',
 13: 'F',
 14: 'L',
 15: ';',
 16: 'D',
 17: ' ',
 18: 'y',
 19: 'Z',
 20: 'j',
 21: ',',
 22: 'V',
 23: 's',
 24: 'E',
 25: '?',
 26: 'X',
 27: 'C',
 28: 'J',
 29: 'O',
 30: 'R',
 31: '6',
 32: '$',
 33: 'n',
 34: 'h',
 35: 'm',
 36: 't',
 37: '(',
 38: 'w',
 39: '.',
 40: 'H',
 41: 'i',
 42: '"',
 43: 'z',
 44: 'Y',
 45: '8',
 46: '\n',
 47: 'I',
 48: '2',
 49: '7',
 50: 'r',
 51: 'Q',
 52: 'd',
 53: '_',
 54: 'g',
 55: '!',
 56: '9',
 57: 'l',
 58: 'e',
 59: 'o',
 60: 'T',
 61: ')',
 62: 'S',
 63: ':',
 64: 'U',
 65: 'G',
 66: 'W',
 67: "'",
 68: '`',
 69: 'v',
 70: 'N',
 71: '1',
 72: 'a',
 73: 'M',
 74: '5',
 75: 'p',
 76: 'c',
 77: '@',
 78: 'K',
 79: 'b',
 80: 'B',
 81: 'x',
 82: 'u'}

In [8]:
# key 가 글자 value 가 숫자

char2int = {ch:ii for ii, ch in int2char.items()}

In [9]:
char2int

{'4': 0,
 '%': 1,
 '-': 2,
 '*': 3,
 'k': 4,
 'f': 5,
 '&': 6,
 'A': 7,
 '/': 8,
 'P': 9,
 'q': 10,
 '0': 11,
 '3': 12,
 'F': 13,
 'L': 14,
 ';': 15,
 'D': 16,
 ' ': 17,
 'y': 18,
 'Z': 19,
 'j': 20,
 ',': 21,
 'V': 22,
 's': 23,
 'E': 24,
 '?': 25,
 'X': 26,
 'C': 27,
 'J': 28,
 'O': 29,
 'R': 30,
 '6': 31,
 '$': 32,
 'n': 33,
 'h': 34,
 'm': 35,
 't': 36,
 '(': 37,
 'w': 38,
 '.': 39,
 'H': 40,
 'i': 41,
 '"': 42,
 'z': 43,
 'Y': 44,
 '8': 45,
 '\n': 46,
 'I': 47,
 '2': 48,
 '7': 49,
 'r': 50,
 'Q': 51,
 'd': 52,
 '_': 53,
 'g': 54,
 '!': 55,
 '9': 56,
 'l': 57,
 'e': 58,
 'o': 59,
 'T': 60,
 ')': 61,
 'S': 62,
 ':': 63,
 'U': 64,
 'G': 65,
 'W': 66,
 "'": 67,
 '`': 68,
 'v': 69,
 'N': 70,
 '1': 71,
 'a': 72,
 'M': 73,
 '5': 74,
 'p': 75,
 'c': 76,
 '@': 77,
 'K': 78,
 'b': 79,
 'B': 80,
 'x': 81,
 'u': 82}

In [10]:
#글자들을 숫자로 바꾼다
encoded = np.array([char2int[ch] for ch in text])

In [11]:
encoded[:100]

array([27, 34, 72, 75, 36, 58, 50, 17, 71, 46, 46, 46, 40, 72, 75, 75, 18,
       17,  5, 72, 35, 41, 57, 41, 58, 23, 17, 72, 50, 58, 17, 72, 57, 57,
       17, 72, 57, 41,  4, 58, 15, 17, 58, 69, 58, 50, 18, 17, 82, 33, 34,
       72, 75, 75, 18, 17,  5, 72, 35, 41, 57, 18, 17, 41, 23, 17, 82, 33,
       34, 72, 75, 75, 18, 17, 41, 33, 17, 41, 36, 23, 17, 59, 38, 33, 46,
       38, 72, 18, 39, 46, 46, 24, 69, 58, 50, 18, 36, 34, 41, 33])

In [12]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [13]:
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]
